image: node:latest

stages:
  - build
  - deploy
  
build:
  stage: build
  artifacts:
    when: on_success
    untracked: true
    paths:
      - Procfile
  script:
    - npm install -g ts-node tslint typescript
    - npm install
    - npm run build

deploy:
  stage: deploy
  dependencies: 
    - build
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=bot-wbb --api-key=$HEROKU_API_KEY
  only:
    - master